### ISSUE TITLE
Laser pecker cross-platform client. Any news ???

### ISSUE THREAD

**Issue by davidex720** [yy502/laserpecker#2]
Hi there,
Are there some news about the cross-platform client scheduled for March 2021?
Will it support command line and linux?

Thank you
D

**Comment by yy502** [comment]
no news yet. afaik it's for Win and Mac, not Linux 😔

If I can find time, I'll modify LaserWeb to support LP.

**Comment by davidex720** [comment]
is there any chance to reverse engineer the lp android app?
I mean, the app is necessary to upload files and start an engraving...
Probably we can emulate the app behavior

**Comment by yy502** [comment]
I'm not an expert in reverse engineering apks. Feel free to do it and please share your findings :)
