### ISSUE TITLE
LaserPecker 2

### ISSUE THREAD

**Issue by xHuubx** [yy502/laserpecker#3]
Hi Yi Yu,

I am looking at your progress on the LaserPecker engraving machine with interest. I have seen that you also have a LaserPecker 2. Can you test and engrave the metal front part of a USB-A dongle? I am curious how detailed it can be engraved. 
Would it require a laser marker black to do it or can it engrave it directly ?
Kee up the good work!

Regards,

Huub

**Comment by yy502** [comment]
It will require a black coating, a black whiteboard marker will do. See this post for precision https://www.facebook.com/groups/374697760505822/permalink/454319635876967/
